#pragma once

//
#include <Arduino.h>
#include <FS.h>
#include <vector>

//
// Wubi 86 Chinese Input Method.
//
// The IME sits in front of the editor: while it is active it consumes a-z keys
// to build a Wubi code, looks up candidate hanzi in the on-disk dictionary
// (/wubi86.bin, generated by tools/gen_wubi.py), and emits the chosen hanzi as a
// UTF-8 string for the editor to insert. ASCII typing is untouched when the IME
// is inactive.
//
class IME
{
public:
    // Load the dictionary from the file system (SD card / gfs). Safe to call
    // more than once; returns true when the table is available.
    bool begin();
    bool loaded() const { return _loaded; }

    // Chinese input mode on/off. Toggling clears any in-progress composition.
    bool active() const { return _active; }
    void setActive(bool on);
    void toggle() { setActive(!_active); }

    // Feed a key. Returns true when the IME consumed it (so the caller must NOT
    // forward it to the editor). Returns false to let the editor handle it.
    // On a successful commit, `out` receives the UTF-8 hanzi to insert.
    bool handleKey(int key, String &out);

    // Current composition (the typed Wubi letters), for the candidate bar.
    const String &composition() const { return _code; }

    // Candidates visible on the current page (already best-first).
    const std::vector<String> &candidates() const { return _page; }

    // True when there is something to draw in the candidate bar.
    bool composing() const { return _code.length() > 0; }

    //////////////////////////////////
    // SINGLETON
    static IME &getInstance()
    {
        static IME instance;
        return instance;
    }
    IME(const IME &) = delete;
    IME &operator=(const IME &) = delete;
    //////////////////////////////////

private:
    IME() {}

    // dictionary record: fixed 8 bytes on disk (code[4] + hanzi[3] + flag[1])
    static const int RECORD_SIZE = 8;
    static const int HEADER_SIZE = 8; // magic[4] + count[4]

    bool _loaded = false;
    bool _active = false;

    // The dictionary is streamed from the SD card on demand (it is ~265 KB -
    // too large to hold in the internal heap, and we don't want to depend on
    // PSRAM being present). The file stays open for the whole session.
    File _file;
    uint32_t _count = 0;

    // Read the 4-byte code of record `i` into `out` (NUL-terminated). Returns
    // false on an I/O error.
    bool readCode(uint32_t i, char out[5]);
    // Read the 3-byte UTF-8 hanzi of record `i` into `out` (NUL-terminated).
    bool readHanzi(uint32_t i, char out[4]);

    String _code;                   // typed Wubi letters
    std::vector<String> _all;       // all candidates for the current code
    std::vector<String> _page;      // candidates on the current page
    int _pageStart = 0;             // index into _all of the first page entry
    static const int PAGE_SIZE = 9; // candidates shown / selectable per page

    void reset();          // clear composition state
    void lookup();         // refresh _all from _code
    void buildPage();      // refresh _page from _all + _pageStart
    bool commit(int idx, String &out); // commit page candidate idx (0-based)
};
