#pragma once

//
#include <Arduino.h>
#include <FS.h>
#include <vector>

//
// Wubi 86 Chinese Input Method.
//
// The IME sits in front of the editor: while it is active it consumes a-z keys
// to build a Wubi code, looks up candidate hanzi in the dictionary, and emits
// the chosen hanzi as a UTF-8 string for the editor to insert. ASCII typing is
// untouched when the IME is inactive.
//
// Dictionary source (generated by tools/gen_wubi.py, WUB2 format):
//   - WUBI_EMBEDDED (cardputer-adv): the .bin is compiled into flash via
//     board_build.embed_files and read in place as memory-mapped flash - no SD,
//     no file handle, no per-lookup seeks. Only the 2.7 KB prefix index is
//     copied to RAM.
//   - otherwise: streamed from /wubi86.bin on the SD card (gfs), file kept open
//     between lookups and closed around editor saves.
//
class IME
{
public:
    // Load the dictionary from the file system (SD card / gfs). Safe to call
    // more than once; returns true when the table is available.
    bool begin();
    bool loaded() const { return _loaded; }

    // Release the open dictionary file handle. MUST be called before the editor
    // mutates the SD card's FAT tree (rename/remove during a save): holding a
    // handle open across those operations froze the device. The handle reopens
    // lazily on the next lookup; the RAM index/count survive so no reload cost.
    void suspend();

    // Chinese input mode on/off. Toggling clears any in-progress composition.
    bool active() const { return _active; }
    void setActive(bool on);
    void toggle() { setActive(!_active); }

    // Feed a key. Returns true when the IME consumed it (so the caller must NOT
    // forward it to the editor). Returns false to let the editor handle it.
    // On a successful commit, `out` receives the UTF-8 hanzi to insert.
    bool handleKey(int key, String &out);

    // Current composition (the typed Wubi letters), for the candidate bar.
    const String &composition() const { return _code; }

    // Candidates visible on the current page (already best-first).
    const std::vector<String> &candidates() const { return _page; }

    // True when there is something to draw in the candidate bar.
    bool composing() const { return _code.length() > 0; }

    //////////////////////////////////
    // SINGLETON
    static IME &getInstance()
    {
        static IME instance;
        return instance;
    }
    IME(const IME &) = delete;
    IME &operator=(const IME &) = delete;
    //////////////////////////////////

private:
    IME() {}

    // dictionary record: fixed 8 bytes on disk (code[4] + hanzi[3] + flag[1])
    static const int RECORD_SIZE = 8;
    static const int HEADER_SIZE = 8; // magic[4] + count[4]

    // First-two-letter prefix index (see tools/gen_wubi.py). A flat lower-bound
    // table: entry k = (c0-'a')*26 + (c1-'a') holds the first record index whose
    // code sorts >= that two-letter prefix. Entry INDEX_ENTRIES-1 is a sentinel
    // == _count, so any bucket k covers records [_index[k], _index[k+1]).
    // Loaded into RAM once at begin() (2708 bytes) to skip most binary-search
    // seeks: a query jumps straight to a hundreds-record window on the SD card.
    static const int INDEX_ENTRIES = 26 * 26 + 1; // 677

    bool _loaded = false;
    bool _active = false;

    // Pointer to the whole dictionary blob. In the WUBI_EMBEDDED build this
    // points straight at the flash-mapped array (no RAM cost, no SD); otherwise
    // it is null and records are streamed from the SD file below.
    const uint8_t *_blob = nullptr;
    size_t _blobSize = 0;

    // SD streaming state (unused in the WUBI_EMBEDDED build). The file is kept
    // open between lookups for speed but is closed around editor saves (see
    // suspend()) and reopened lazily.
    File _file;
    bool _open = false; // is _file currently open?
    uint32_t _count = 0;

    // Reopen _file if it was closed by suspend(). Returns true when the handle
    // is ready for reading. Cheap no-op when already open (or when embedded).
    bool ensureOpen();

    // Byte offset of record 0 in the file: HEADER_SIZE for the old WUB1 format,
    // HEADER_SIZE + INDEX_ENTRIES*4 for WUB2 (which carries the prefix index).
    size_t _recordBase = HEADER_SIZE;
    // The prefix index, or empty when reading a legacy WUB1 file without one.
    std::vector<uint32_t> _index;

    // Narrow the search to the record window [lo,hi) that could match the typed
    // code, using the RAM index. Falls back to the full table when no index is
    // loaded or the code has no usable leading letters.
    void searchWindow(const char *code, int len, uint32_t &lo, uint32_t &hi);

    // Parse the WUB1/WUB2 header + prefix index from a contiguous buffer
    // holding at least the header (+ the whole index for WUB2). Fills _count,
    // _recordBase and _index. `total` is the whole dictionary size.
    bool parseHeader(const uint8_t *hdrIndex, size_t total);

    // Read exactly `n` bytes from the current file position (SD reads short-read).
    bool readFull(uint8_t *dst, size_t n);
    // Read the 4-byte code of record `i` into `out` (NUL-terminated). Returns
    // false on an I/O error.
    bool readCode(uint32_t i, char out[5]);
    // Read the 3-byte UTF-8 hanzi of record `i` into `out` (NUL-terminated).
    bool readHanzi(uint32_t i, char out[4]);

    String _code;                   // typed Wubi letters
    std::vector<String> _all;       // all candidates for the current code
    std::vector<String> _page;      // candidates on the current page
    int _pageStart = 0;             // index into _all of the first page entry
    static const int PAGE_SIZE = 9; // candidates shown / selectable per page

    void reset();          // clear composition state
    void lookup();         // refresh _all from _code
    void buildPage();      // refresh _page from _all + _pageStart
    bool commit(int idx, String &out); // commit page candidate idx (0-based)
};
