#include "IME.h"
#include "app/app.h"
#include "display/display.h"

//
// Dictionary file lives on the same file system as the journals (SD card on the
// Cardputer). Generated by tools/gen_wubi.py.
//
static const char *WUBI_PATH = "/wubi86.bin";
static const uint8_t WUBI_MAGIC[4] = {'W', 'U', 'B', '1'};

bool IME::begin()
{
    if (_loaded)
        return true;

    if (!gfs())
        return false;

    File f = gfs()->open(WUBI_PATH, "r");
    if (!f)
    {
        _log("[IME] dictionary %s not found\n", WUBI_PATH);
        return false;
    }

    size_t size = f.size();
    if (size < 8)
    {
        _log("[IME] dictionary too small (%u bytes)\n", (unsigned)size);
        f.close();
        return false;
    }

    uint8_t header[8];
    if (f.read(header, 8) != 8 || memcmp(header, WUBI_MAGIC, 4) != 0)
    {
        _log("[IME] bad dictionary magic\n");
        f.close();
        return false;
    }

    _count = (uint32_t)header[4] | ((uint32_t)header[5] << 8) |
             ((uint32_t)header[6] << 16) | ((uint32_t)header[7] << 24);

    size_t bytes = (size_t)_count * RECORD_SIZE;
    if (8 + bytes > size)
    {
        _log("[IME] dictionary truncated: need %u, have %u\n",
             (unsigned)(8 + bytes), (unsigned)size);
        f.close();
        return false;
    }

    // Prefer PSRAM for the table; fall back to regular heap if unavailable.
    _data = (uint8_t *)heap_caps_malloc(bytes, MALLOC_CAP_SPIRAM);
    if (!_data)
        _data = (uint8_t *)malloc(bytes);
    if (!_data)
    {
        _log("[IME] out of memory for %u records\n", (unsigned)_count);
        f.close();
        return false;
    }

    size_t got = f.read(_data, bytes);
    f.close();
    if (got != bytes)
    {
        _log("[IME] short read %u/%u\n", (unsigned)got, (unsigned)bytes);
        free(_data);
        _data = nullptr;
        return false;
    }

    _loaded = true;
    _log("[IME] loaded %u Wubi records\n", (unsigned)_count);
    return true;
}

void IME::setActive(bool on)
{
    _active = on;
    reset();
}

void IME::reset()
{
    _code = "";
    _all.clear();
    _page.clear();
    _pageStart = 0;
}

// Read the 4-byte code of record `i` into a comparable C string.
static void record_code(const uint8_t *data, uint32_t i, char out[5])
{
    const uint8_t *rec = data + (size_t)i * 8;
    int n = 0;
    for (; n < 4 && rec[n]; n++)
        out[n] = (char)rec[n];
    out[n] = '\0';
}

void IME::lookup()
{
    _all.clear();
    _pageStart = 0;

    if (!_loaded || _code.length() == 0)
    {
        buildPage();
        return;
    }

    const char *q = _code.c_str();
    int qlen = _code.length();

    // Binary search for the first record whose code >= the typed prefix.
    uint32_t lo = 0, hi = _count;
    while (lo < hi)
    {
        uint32_t mid = lo + (hi - lo) / 2;
        char code[5];
        record_code(_data, mid, code);
        if (strncmp(code, q, qlen) < 0)
            lo = mid + 1;
        else
            hi = mid;
    }

    // Walk forward collecting every record whose code starts with the prefix,
    // de-duplicating hanzi (the table can list the same char at several weights).
    for (uint32_t i = lo; i < _count; i++)
    {
        char code[5];
        record_code(_data, i, code);
        if (strncmp(code, q, qlen) != 0)
            break;

        const uint8_t *rec = _data + (size_t)i * 8;
        char hz[4] = {(char)rec[4], (char)rec[5], (char)rec[6], '\0'};
        String h(hz);

        bool dup = false;
        for (auto &e : _all)
            if (e == h)
            {
                dup = true;
                break;
            }
        if (!dup)
            _all.push_back(h);

        // cap to keep paging snappy
        if (_all.size() >= 60)
            break;
    }

    buildPage();
}

void IME::buildPage()
{
    _page.clear();
    for (int i = _pageStart; i < (int)_all.size() && (int)_page.size() < PAGE_SIZE; i++)
        _page.push_back(_all[i]);
}

bool IME::commit(int idx, String &out)
{
    if (idx < 0 || idx >= (int)_page.size())
        return false;
    out = _page[idx];
    reset();
    return true;
}

bool IME::handleKey(int key, String &out)
{
    if (!_active)
        return false;

    // letters a-z (and A-Z) build the Wubi code
    if ((key >= 'a' && key <= 'z') || (key >= 'A' && key <= 'Z'))
    {
        if (_code.length() < 4)
        {
            _code += (char)tolower(key);
            lookup();
        }
        return true;
    }

    // nothing in progress: only the explicit control keys below are ours,
    // everything else (including normal punctuation) goes to the editor.
    if (_code.length() == 0)
        return false;

    // digits select a candidate on the current page (1..9)
    if (key >= '1' && key <= '9')
    {
        if (commit(key - '1', out))
            return true;
        return true; // consumed even if out of range
    }

    // space commits the first candidate
    if (key == ' ')
    {
        if (_page.size() > 0)
            commit(0, out);
        else
            reset(); // no match - just drop the bad code
        return true;
    }

    // enter commits the typed letters as-is? No - clear, treat enter as commit#1
    if (key == '\n')
    {
        if (_page.size() > 0)
            commit(0, out);
        else
            reset();
        return true;
    }

    // backspace removes the last code letter
    if (key == '\b')
    {
        _code.remove(_code.length() - 1);
        if (_code.length() == 0)
            reset();
        else
            lookup();
        return true;
    }

    // ESC cancels the whole composition
    if (key == 27)
    {
        reset();
        return true;
    }

    // paging: ';' / ',' previous page, '\'' / '.' next page
    if (key == ';' || key == ',')
    {
        if (_pageStart - PAGE_SIZE >= 0)
        {
            _pageStart -= PAGE_SIZE;
            buildPage();
        }
        return true;
    }
    if (key == '\'' || key == '.')
    {
        if (_pageStart + PAGE_SIZE < (int)_all.size())
        {
            _pageStart += PAGE_SIZE;
            buildPage();
        }
        return true;
    }

    // Any other key while composing (e.g. punctuation): commit the best
    // candidate and consume the key. The key itself is dropped rather than
    // forwarded, which keeps the behaviour predictable - the user can press the
    // punctuation again after the hanzi lands.
    if (_page.size() > 0)
    {
        commit(0, out);
        return true;
    }

    // Unmatched code + unknown key: drop the dead code, consume the key.
    reset();
    return true;
}
